### ISSUE TITLE
Support for ignoring other typedefs

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [homer0/jsdoc-ts-utils#33]
I'm trying to add jsdoc comments for some old code that works with JQuery APIs, and I have a `@typedef` that VSCode is happy with but which breaks JSDoc:
```js
/**
 * @typedef {JQuery.AjaxSettings['success']} JQueryOnSuccess
 */
```
The `['success']` indexed access is the part that JSDoc doesn't support (and I can't see another way to do it). I can't get `import` inside the `@typedef` to work because of how the types for JQuery are defined, but without using `import` the `typedefImports` code doesn't trigger, so I'm stuck.

A feature to clear lines containing indexed access would work, but since that sounds pretty specific I was thinking more along the lines of `@jsdoc-ignore-next-line` to simply ignore whatever comes next.

**Comment by ehoogeveen-medweb** [comment]
Another thing that might work as a general feature is to ignore all instances with double curly braces, as VSCode accepts TypeScript syntax inside double braces:
```js
/**
 * @typedef {{(param1: string, param2: number) => string}} TypescriptStyleFunctionType
 */
```

**Comment by homer0** [comment]
@ehoogeveen-medweb Sorry it took me so long to update this!

**Comment by ehoogeveen-medweb** [comment]
Thanks, I'll update our dependencies and try it out soon!
