### ISSUE TITLE
feature request: Merge properties of intersected type definitions

### ISSUE THREAD

**Issue by eddielee394** [homer0/jsdoc-ts-utils#36]
First, thanks for putting together this really useful plugin.  

It'd be great if when intersecting multiple typedefs the properties would actually get merged in the final output.  For example:   

```
/**
 * @typedef {Object} Entity
 * @property {string} shape ...
 * @property {string} name  ...
 */

/**
 * @typedef {Object} PersonProperties
 * @property {number} age    ...
 * @property {number} height ...
 */

/**
 * @typedef {Entity & PersonProperties} Person
 */

// output
/**
 * @typedef {Object} Person
 * @property {string} shape ... <--merged from Entity
 * @property {string} name  ... <-- merged from Entity
 * @property {number} age   ... <-- merged from PersonProperties
 * @property {number} height ... <-- merged from PersonProperties
 */
```

This is a bit different from the current `extendTypes` functionality, as that will extend `Person` from the type `Entity` where the output properties on the `Person` typedef are only `PersonProperties`.  Per your example: 

```
/**
* @typedef {Entity} Person
* @property {number} age ...
* @property {number} height ...
*/
```

**Comment by homer0** [comment]
Hi @eddielee394 👋 !

First, **I'm so sorry**, I never saw the notifications on this repo.

And double sorry that this is the answer 😞: I don't think this would be easy to achieve, as with the current implementation, the logic is basically "find `{A & B}` and create a type based on `A` with the props from `B`", and JSDoc would take care of correctly linking to `A`, and it's possible parent (if there's one).

Now, to pull all the props from `A`, the plugin would have to track it down (and it's possible parent(s)), and/or validate if it comes from a `typedef.js`. This plugin is based on parsing strings on the current file it's checking, it doesn't have reference of all the types in the project.

Sorry, and double sorry that took me so much to respond!
