### ISSUE TITLE
Update JSDoc dependency to version 4

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [homer0/jsdoc-ts-utils#38]
JSDoc version 4.0.0 was released in November 2022, see https://github.com/jsdoc/jsdoc/blob/main/CHANGES.md
The main change is that it no longer uses the taffydb package due to a security vulnerability.

Unfortunately because it's a major version bump, this package still requires jsdoc v3.6.11 with that vulnerability.

Could you update the dependency to version 4? It might also make more sense as a `peerDependency`, although I guess that would have prevented me from updating to JSDoc v4 at all.

**Comment by homer0** [comment]
Hi @ehoogeveen-medweb 👋 !

First, I'm so sorry, I never saw the notifications on this repo.

I just updated the project a little bit, and fixed the dep for JSDoc.

I hope it helps!
